version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  build:
    commands:
      - echo Packaging Lambda function...
      - zip function.zip index.js
artifacts:
  files:
    - function.zip
